local M = {}
return M
--
-- function M.setup()
-- 	local lspconfig = require("lspconfig")
--
-- 	-- pylsp only: language intelligence, no formatting or linting
-- 	lspconfig.pylsp.setup({
-- 		cmd = { "pylsp" },
-- 		settings = {
-- 			pylsp = {
-- 				plugins = {
-- 					-- keep core Jedi features
-- 					jedi_completion = { enabled = true },
-- 					jedi_hover = { enabled = true },
-- 					jedi_references = { enabled = true },
-- 					jedi_signature_help = { enabled = true },
-- 					jedi_symbols = { enabled = true, all_scopes = true },
-- 					jedi_definition = { enabled = true },
--
-- 					-- disable linters/formatters inside pylsp (ruff/none-ls will handle)
-- 					pycodestyle = { enabled = false },
-- 					pyflakes = { enabled = false },
-- 					mccabe = { enabled = false },
-- 					pylint = { enabled = false },
--
-- 					-- disable formatters
-- 					autopep8 = { enabled = false },
-- 					yapf = { enabled = false },
-- 					black = { enabled = false },
--
-- 					-- optional: keep rope disabled unless you use it
-- 					rope = { enabled = false },
-- 				},
-- 			},
-- 		},
-- 		on_attach = function(client, bufnr)
-- 			-- critical: pylsp must not format if none-ls formats
-- 			client.server_capabilities.documentFormattingProvider = false
-- 			client.server_capabilities.documentRangeFormattingProvider = false
-- 		end,
-- 	})
-- end
--
-- return M
