return {
	-- "neovim/nvim-lspconfig",
	-- event = { "BufReadPre", "BufNewFile" },
	-- dependencies = {
	-- 	"hrsh7th/cmp-nvim-lsp",
	-- 	{ "antosha417/nvim-lsp-file-operations", config = true },
	-- 	{ "folke/lazydev.nvim", opts = {} },
	-- },
	-- config = function()
	-- 	local keymap = vim.keymap -- for conciseness
	--
	-- 	vim.api.nvim_create_autocmd("LspAttach", {
	-- 		group = vim.api.nvim_create_augroup("UserLspConfig", {}),
	-- 		callback = function(ev)
	-- 			-- Buffer local mappings.
	-- 			-- See `:help vim.lsp.*` for documentation on any of the below functions
	-- 			local opts = { buffer = ev.buf, silent = true }
	-- 			-- set keybinds
	-- 			opts.desc = "Show LSP references"
	-- 			keymap.set("n", "gR", "<cmd>Telescope lsp_references<CR>", opts) -- show definition, references
	--
	-- 			opts.desc = "Go to declaration"
	-- 			keymap.set("n", "gD", vim.lsp.buf.declaration, opts) -- go to declaration
	--
	-- 			opts.desc = "Show LSP definitions"
	-- 			keymap.set("n", "gd", "<cmd>Telescope lsp_definitions<CR>", opts) -- show lsp definitions
	--
	-- 			opts.desc = "Show LSP implementations"
	-- 			keymap.set("n", "gi", "<cmd>Telescope lsp_implementations<CR>", opts) -- show lsp implementations
	--
	-- 			opts.desc = "Show LSP type definitions"
	-- 			keymap.set("n", "gt", "<cmd>Telescope lsp_type_definitions<CR>", opts) -- show lsp type definitions
	--
	-- 			opts.desc = "See available code actions"
	-- 			keymap.set({ "n", "v" }, "<leader>ca", vim.lsp.buf.code_action, opts) -- see available code actions, in visual mode will apply to selection
	--
	-- 			opts.desc = "Smart rename"
	-- 			keymap.set("n", "<leader>rn", vim.lsp.buf.rename, opts) -- smart rename
	--
	-- 			opts.desc = "Show buffer diagnostics"
	-- 			keymap.set("n", "<leader>D", "<cmd>Telescope diagnostics bufnr=0<CR>", opts) -- show  diagnostics for file
	--
	-- 			opts.desc = "Show line diagnostics"
	-- 			keymap.set("n", "<leader>d", vim.diagnostic.open_float, opts) -- show diagnostics for line
	--
	-- 			-- opts.desc = 'Go to previous diagnostic'
	-- 			-- keymap.set('n', '[d', vim.diagnostic.goto_prev, opts) -- jump to previous diagnostic in buffer
	-- 			--
	-- 			-- opts.desc = 'Go to next diagnostic'
	-- 			-- keymap.set('n', ']d', vim.diagnostic.goto_next, opts) -- jump to next diagnostic in buffer
	--
	-- 			opts.desc = "Show documentation for what is under cursor"
	-- 			keymap.set("n", "K", vim.lsp.buf.hover, opts) -- show documentation for what is under cursor
	--
	-- 			opts.desc = "Restart LSP"
	-- 			keymap.set("n", "<leader>rs", ":LspRestart<CR>", opts) -- mapping to restart lsp if necessary
	-- 		end,
	-- 	})
	--
	-- 	-- vim.diagnostic.config({
	-- 	-- 	virtual_text = true,
	-- 	-- })
	-- 	--
	-- 	-- -- Change the Diagnostic symbols in the sign column (gutter)
	-- 	-- local signs = { Error = " ", Warn = " ", Hint = "󰠠 ", Info = " " }
	-- 	--
	-- 	-- for type, icon in pairs(signs) do
	-- 	-- 	local name = "DiagnosticSign" .. type
	-- 	-- 	vim.api.nvim_set_hl(0, name, { default = true, link = name })
	-- 	-- 	vim.fn.sign_define(name, { text = icon, texthl = name, numhl = "" })
	-- 	-- end
	--
	-- 	vim.diagnostic.config({
	-- 		virtual_lines = true,
	-- 		-- virtual_text = true,
	-- 		underline = true,
	-- 		update_in_insert = false,
	-- 		severity_sort = true,
	-- 		float = {
	-- 			border = "rounded",
	-- 			source = true,
	-- 		},
	-- 		signs = {
	-- 			text = {
	-- 				[vim.diagnostic.severity.ERROR] = "󰅚 ",
	-- 				[vim.diagnostic.severity.WARN] = "󰀪 ",
	-- 				[vim.diagnostic.severity.INFO] = "󰋽 ",
	-- 				[vim.diagnostic.severity.HINT] = "󰌶 ",
	-- 			},
	-- 			numhl = {
	-- 				[vim.diagnostic.severity.ERROR] = "ErrorMsg",
	-- 				[vim.diagnostic.severity.WARN] = "WarningMsg",
	-- 			},
	-- 		},
	-- 	})
	--
	-- 	-- vim.lsp.config['texlab'] = {
	-- 	--   settings = {
	-- 	--     texlab = {
	-- 	--       build = {
	-- 	--         executable = 'latexmk',
	-- 	--         args = {
	-- 	--           '-pdf',
	-- 	--           '-interaction=nonstopmode',
	-- 	--           '-file-line-error',
	-- 	--           '-silent',
	-- 	--           '-synctex=1',
	-- 	--           '-shell-escape',
	-- 	--           '-outdir=build',
	-- 	--           '%f',
	-- 	--         },
	-- 	--         forwardSearchAfter = true,
	-- 	--         onSave = true,
	-- 	--       },
	-- 	--       chktex = {
	-- 	--         onOpenAndSave = true,
	-- 	--         onEdit = true,
	-- 	--         additionalArgs = { '-n3' },
	-- 	--       },
	-- 	--       diagnosticsDelay = 300,
	-- 	--       forwardSearch = {
	-- 	--         executable = 'SumatraPDF',
	-- 	--         args = {
	-- 	--           '-reuse-instance',
	-- 	--           '-forward-search',
	-- 	--           'verbose',
	-- 	--           'file-line-error',
	-- 	--           '%p', -- path to PDF
	-- 	--           '%f',
	-- 	--           '%l', -- forward search to line
	-- 	--           -- '-inverse-search',
	-- 	--           -- [[nvim --headless -c "VimtexInverseSearch %f %l"]],
	-- 	--         },
	-- 	--       },
	-- 	--       latexFormatter = 'latexindent',
	-- 	--       latexindent = {
	-- 	--         modifyLineBreaks = true,
	-- 	--       },
	-- 	--     },
	-- 	--   },
	-- 	-- }
	-- 	--
	-- 	vim.lsp.config["ltex_plus"] = {
	-- 		filetypes = { "typst", "typ", "bib", "bibtex", "markdown", "text", "latex" },
	-- 		settings = {
	-- 			ltex = {
	-- 				language = { "en-US" },
	-- 				enabled = { "typst", "typ", "bib", "bibtex", "markdown", "text", "latex" },
	-- 				disabledRules = {
	-- 					["en-US"] = {
	-- 						"WHITESPACE_RULE", -- “Don’t put a space before/after parenthesis”
	-- 						"UPPERCASE_SENTENCE_START", -- false positive with math
	-- 						"EN_QUOTES", -- disables English quote style enforcement
	-- 						"COMMA_PARENTHESIS_WHITESPACE",
	-- 						"DOUBLE_PUNCTUATION",
	-- 					},
	-- 				},
	-- 				dictionary = {
	-- 					["en-US"] = {
	-- 						"supremum",
	-- 						"infimum",
	-- 						"Int",
	-- 						"Apostol",
	-- 						"subcover",
	-- 						":~/.config/nvim/ltex/ltex.dictionary.en-US.txt",
	-- 					},
	-- 				},
	-- 				logLevel = "error",
	-- 			},
	-- 		},
	-- 	}
	--
	-- 	-- vim.lsp.config["pylsp"] = {
	-- 	-- 	settings = {
	-- 	-- 		pylsp = {
	-- 	-- 			plugins = {
	-- 	-- 				jedi_completion = { enabled = true },
	-- 	-- 				jedi_hover = { enabled = true },
	-- 	-- 				jedi_references = { enabled = true },
	-- 	-- 				jedi_signature_help = { enabled = true },
	-- 	-- 				jedi_symbols = { enabled = true, all_scopes = true },
	-- 	-- 				jedi_definition = { enabled = true },
	-- 	--
	-- 	-- 				pycodestyle = { enabled = false },
	-- 	-- 				pyflakes = { enabled = false },
	-- 	-- 				mccabe = { enabled = false },
	-- 	--
	-- 	-- 				yapf = { enabled = false },
	-- 	-- 				autopep8 = { enabled = false },
	-- 	-- 				black = { enabled = true }, -- enable if you want autoformatting
	-- 	-- 			},
	-- 	-- 		},
	-- 	-- 	},
	-- 	-- }
	--
	-- 	-- vim.lsp.config["ruff"] = {
	-- 	-- 	init_options = {
	-- 	-- 		settings = {
	-- 	-- 			-- Ruff language server settings go here
	-- 	-- 		},
	-- 	-- 	},
	-- 	-- }
	--
	-- 	vim.lsp.config["tinymist"] = {
	-- 		cmd = { "tinymist" },
	-- 		filetypes = { "typst" },
	-- 		settings = {
	-- 			formattermode = "typstyle",
	-- 			exportPdf = "onSave",
	-- 		},
	-- 		on_attach = function(client, bufnr)
	-- 			-- vim.keymap.set("n", "<leader>ti", function()
	-- 			-- 	client:exec_cmd({
	-- 			-- 		title = "pin",
	-- 			-- 		command = "tinymist.pinMain",
	-- 			-- 		arguments = { vim.api.nvim_buf_get_name(0) },
	-- 			-- 	}, { bufnr = bufnr })
	-- 			-- end, { desc = "[T]inymist p[I]n", noremap = true })
	--
	-- 			vim.keymap.set("n", "<leader>tu", function()
	-- 				client:exec_cmd({
	-- 					title = "unpin",
	-- 					command = "tinymist.pinMain",
	-- 					arguments = { vim.v.null },
	-- 				}, { bufnr = bufnr })
	-- 			end, { desc = "[T]inymist [U]npin", noremap = true })
	-- 		end,
	-- 	}
	-- end,
}
